services:
  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web
    environment:
      OPENAI_API_KEY: "gptyyds"
      CODE: "587456" # 如果你想要设置页面的访问密码，请修改这里
      BASE_URL: "http://freegpt35:3040"
      CUSTOM_MODELS: "-all,+gpt-3.5-turbo"
    depends_on:
      - freegpt35

  freegpt35:
    image: missuo/freegpt35:latest
    restart: always

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
